[package]
name = "arrowflaz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "4.0.0-SNAPSHOT"
arrow = "4.4.0"
tokio = { version = "1.7.0", features = ["full"] }
